name: 'aemo_electricity'
version: '1.0.0'

profile: 'aemo_electricity'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Env vars used:
  # - DBT_SCHEMA: schema name (default: aemo)
  # - csv_archive_path, path_root: for abfss:// paths in Fabric
  # - download_limit: number of files to download per source (default: 2)
  
  # Download settings
  daily_source: aemo  # 'aemo' (default, no rate limits) or 'github' for historical archive

on-run-start:
  - "{{ download() }}"
  - "{{ import_metadata() }}"

on-run-end:
  - "{{ export_metadata() }}"

models:
  aemo_electricity:
    dimensions:
      +materialized: table
    marts:
      +materialized: incremental

