aemo_electricity:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ':memory:'
      database: ducklake
      threads: 1
      schema: "{{ env_var('DBT_SCHEMA', 'aemo') }}"
      extensions:
        - parquet
        - azure
        - httpfs
        - json
        - sqlite
        - ducklake
        - name: zipfs
          repo: community
      attach:
        - path: ducklake:sqlite:/lakehouse/default/Files/metadata.db
          alias: ducklake
          options:
            data_path: "abfss://{{ env_var('FABRIC_WORKSPACE', 'duckrun') }}@onelake.dfs.fabric.microsoft.com/{{ env_var('FABRIC_LAKEHOUSE', 'dbt') }}.Lakehouse/Tables"