aemo_electricity:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ':memory:'
      database: ducklake
      threads: 1
      schema: "{{ env_var('DBT_SCHEMA', 'aemo') }}"
      extensions:
        - parquet
        - azure
        - httpfs
        - json
        - ducklake
        - name: zipfs
          repo: community
      attach:
        - path: "ducklake:{{ env_var('DUCKLAKE_METADATA_PATH', '/tmp/metadata.db') }}"
          alias: ducklake
          options:
            data_path: "{{ env_var('ROOT_PATH', 'abfss://duckrun@onelake.dfs.fabric.microsoft.com/dbt.Lakehouse') }}/Tables"