/// Fact table combining SCADA dispatch and price data from the Australian NEM.
/// Grain: one row per 5-minute dispatch interval per generator unit (DUID).
/// Combines daily historical data with intraday updates.
table fct_summary
	sourceLineageTag: [aemo].[fct_summary]

	/// Dispatch date
	column date
		dataType: dateTime
		formatString: yyyy-MM-dd
		sourceColumn: date
		sourceLineageTag: date
		summarizeBy: none

	/// Time of day as HHMM integer (e.g. 1430 = 2:30 PM)
	column time
		dataType: int64
		sourceColumn: time
		sourceLineageTag: time
		summarizeBy: none

	/// Generator unit identifier — foreign key to dim_duid
	column DUID
		dataType: string
		sourceColumn: DUID
		sourceLineageTag: DUID
		summarizeBy: none

	/// Power output in megawatts (MW) for this 5-minute interval
	column mw
		dataType: decimal
		formatString: #,##0.00
		sourceColumn: mw
		sourceLineageTag: mw
		summarizeBy: sum

	/// Regional reference price in AUD per megawatt-hour ($/MWh)
	column price
		dataType: decimal
		formatString: $#,##0.00
		sourceColumn: price
		sourceLineageTag: price
		summarizeBy: none

	/// Timestamp of the latest data refresh cutoff
	column cutoff
		dataType: dateTime
		formatString: yyyy-MM-dd HH:mm
		sourceColumn: cutoff
		sourceLineageTag: cutoff
		summarizeBy: none

	/// Total megawatts across all selected generators and time periods
	measure 'Total MW' = SUM(fct_summary[mw])
		formatString: #,##0

	/// Total megawatt-hours. Divides MW by 12 because each row is a 5-minute interval (60/5 = 12).
	measure 'Total MWh' = SUM(fct_summary[mw]) / 12
		formatString: #,##0

	/// Average electricity price in AUD per MWh across selected data
	measure 'Avg Price' = AVERAGE(fct_summary[price])
		formatString: $#,##0.00

	/// Count of distinct generator units (DUIDs) in the current selection
	measure 'Generator Count' = DISTINCTCOUNT(fct_summary[DUID])
		formatString: #,##0

	/// Most recent data refresh timestamp, ignoring all filters
	measure 'Latest Update' = CALCULATE(MAX(fct_summary[cutoff]), REMOVEFILTERS())
		formatString: yyyy-MM-dd HH:mm

	partition fct_summary = entity
		mode: directLake
		source
			entityName: fct_summary
			expressionSource: DirectLake
			schemaName: aemo
